### PR TITLE
remove esri-loader defaut exports (and minor README fix)

### PR DESCRIPTION
**Pull request by tomwayson**
next step in #254

### CODE REVIEW

**Review by gavinr — APPROVED** [review]
Looks good to me! Do we need to add any notes to the README about this change? Or will that be in the changelog?

**Comment by tomwayson** [comment]
Thx, this will be in changelog and part of a breaking change.

**Review by jwasilgeo — APPROVED** [review]
Looks good, thanks!

**Review by odoe — APPROVED** [review]
LGTM!

**Pull request merged**
