### PR TITLE
fix bug; dojoRequire's callback should been a Function  and the param…

### PR DESCRIPTION
**Pull request by guzhongren**
example:    https://github.com/guzhongren/YanqiProject/blob/5f04deb69d91304b436589240d2c488f90c8a6a0/src/components/baseComponets/esriMap/index.tsx#L27

in my project,if use the original esri-loader, compile will not pass, it should be like AMD, so....

### CODE REVIEW

**Comment by tomwayson** [comment]
Good catch @guzhongren 

The yarn.lockfile needs to be be removed before this gets merged. The best thing to do is add a commit that adds `yarn.lock` to the .gitignore file.

Would you be able to do that to this PR?

**Comment by davetimmins** [comment]
@guzhongren your code still looks incorrect. You're mixing the usage of esri-loader and esri-loader-react, if you only want to use esri-loader then you should be calling bootstrap, otherwise you should be calling `createMap` from the `ready` property on the esri-loader-react component e.g.

```
<EsriLoader options={options} ready={this.createMap} />
```

all esri-loader-react really does is wrap the call to bootstrap in the componentDidMount lifecycle event, that's what the blog post was showing.

**Comment by guzhongren** [comment]
### rePR

**Comment by tomwayson** [comment]
Thanks @guzhongren 

I was hoping we could have a better type for `callback`, but I haven't been able to find a good example of how to specify that the type is a function w/ an unknown number of arguments w/ unknown types. The closest I can find is using [rest parameters](https://stackoverflow.com/a/12907426/656010), which looks right, but I'm not totally sure. Have you tried something like:

```js
export function dojoRequire(modules: string[], callback: (...modules: any[]) => void) {
```

I'd really appreciate if you could, b/c it seems that you're actually using the TS code (all of my examples/tests use UMD ouput, not the TS directly).

**Comment by guzhongren** [comment]
hi, as you said, i used your suggestion ,my project worked well, i'm sorry for the type of "Function"

**Pull request merged**
