### PR TITLE
handle script load errors

### LINKED ISSUE #14: Handle script load errors
As suggested by @davetimmins in https://github.com/tomwayson/esri-loader/pull/13#issuecomment-290962974

I've actually [implemented this in the ember version](https://github.com/Esri/ember-esri-loader/blob/c8688f547b3d8d63a85ce94f1985adc5e40b85bd/addon/services/esri-loader.js#L54-L56) and that could be used for reference.

### PR DESCRIPTION
**Pull request by tomwayson**
resolves #14

### CODE REVIEW

**Comment by davetimmins** [comment]
Looks like `script.removeEventListener('error', onScriptError, false);` should be called when there is no error too i.e. in the `script.onload` body

**Comment by tomwayson** [comment]
I _think_ you are right @davetimmins, but am not sure. And here I thought I was going above and beyond by removing a listener for an event that should only ever happen once anyway.

As I mention in https://github.com/Esri/esri-loader/issues/14#issuecomment-343059814, I'm about to push a promise-based branch that uses `addEventListener` entirely instead of `onload` and `onerror`. I'll look into having the `'load'` callbacks remove the `'error'` callbacks and vice versa, or at the very least ping you on the PR for suggestions.

**Comment by tomwayson** [comment]
FYI - I didn't add the change (yet) to #48 to "cross remove" the load/error listeners, but it would go [hereish](https://github.com/Esri/esri-loader/blob/6e35ef755fe75d6f8ebdbc1b0bf466528d5f9433/src/esri-loader.ts#L36-L56). Seems like I'd need to replace those functions w/ a single function that added then removed both listeners, but right now those functions are called by the deprecated functions, so it would be easier once those are removed.

**Comment by tomwayson** [comment]
FYI - I've addressed this in https://github.com/Esri/esri-loader/pull/48/commits/2023d6ccc0743d9c637caf4dd7c80c6fda2c43df

I couldn't figure out how to "cross remove" them w/o moving them into a single function, there's a bit of a 🐔 and :egg: situation, but that will be easier after removing `bootstrap()` and `dojoRequire()` and there's no longer any need to keep them as individual functions.

**Pull request merged**
